// <auto-generated />
namespace ResQ.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class theEnd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(theEnd));
        
        string IMigrationMetadata.Id
        {
            get { return "201412140843048_theEnd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
